language: objective-c
osx_image: xcode7.2

install: 
  - git clone https://github.com/Electrode-iOS/ELJSBridge.git ../ELJSBridge
  - git clone https://github.com/Electrode-iOS/ELFoundation.git ../ELFoundation
  - git clone https://github.com/Electrode-iOS/ELLog.git ../ELLog

script:
   - xctool -project ELHybridWeb.xcodeproj -scheme ELHybridWeb -sdk iphonesimulator build test
