language: objective-c
osx_image: xcode9.1

install: 
  - carthage update --no-build

script:
   - xcodebuild -project ELHybridWeb.xcodeproj -scheme ELHybridWeb -sdk iphonesimulator test -destination 'OS=10.0,name=iPhone 6s Plus' CODE_SIGNING_REQUIRED=NO
