language: objective-c
osx_image: xcode8

install: 
  - carthage update --no-build

script:
   - xcodebuild -project ELHybridWeb.xcodeproj -scheme ELHybridWeb -sdk iphonesimulator test -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' CODE_SIGNING_REQUIRED=NO
